language: python

python:
    - "2.7"

install:
    - pip install flake8
    - pip install -r requirements.txt

notifications:
    email:
        - pjdufour.dev@gmail.com

before_script:
    flake8 geositeserver

script: python -m unittest geositeserver.tests.test
